#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs
# Chat: https://chat.vector.dev
# ------------------------------------------------------------------------------

[sources.docker_logs]
type = "docker_logs"
include_containers = ["teachyourselfmath", "vivekn.dev", "workdiff"]

[transforms.parse_json]
type = "remap"
inputs = ["docker_logs"]
source = '''
.message = to_string!(.message)
json, err = parse_json(.message)
if err == null {
  . = json
} else {
  abort
}
'''

[sinks.clickhouse]
type = "clickhouse"
inputs = ["parse_json"]
endpoint = "http://192.168.1.100:8123"
database = "default"
table = "app_logs"
compression = "gzip"
skip_unknown_fields = true
auth.strategy = "basic"
auth.user = "default"
auth.password = "${CLICKHOUSE_PASSWORD}"
