server {
    server_name nattukaka.dev www.nattukaka.dev;

    root /var/www/nattukaka.dev;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/nattukaka.dev/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/nattukaka.dev/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = www.nattukaka.dev) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = nattukaka.dev) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name nattukaka.dev www.nattukaka.dev;
    return 404; # managed by Certbot
}